In this notebook, we are going to cover the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* using @tf.function (a way to speed up your regular python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself

**Introduction to Tensors**

In [1]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
# create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimension of a tensor (ndim stands for number of dimensions
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of our vector
vector.ndim

1

In [6]:
# create a matrix *has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.,]], dtype=tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:
* scalar: a single number
* vector: a number with direction (e.g sind speed and direction)
* matrix: a 2 dimensional array of numbners
* tensor: en n dimensional array of numbers (when n can be any numnber, a - dimensional tensor is a scalar, a 1 dimensional tensor is a vector)

### creating tensors with tf.Variable

In [12]:
# Create the same tensor with tf.Variable() as aboce
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [15]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
# let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

note: rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However, in doubt, use tf.constant and change it later if needed.

### **Creating random tensors**

random tensor are tensor of some arbitrary size which contains random numbers

In [18]:
# let's create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### shuffle the order of elements in a tensor

In [19]:
# suffle a tensor (valuable for when you want to suffle your dat so the inherent order doesn't affect learning)

not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [20]:
# shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

Exercise: read through TensorFlow decumentation on random seed generation and practice writing 5 random tensors and shuffle them

In [22]:
rand_tensor_1 = tf.random.Generator.from_seed(42)
rand_tensor_1 = rand_tensor_1.normal(shape=(5, 5))

rand_tensor_2 = tf.random.Generator.from_seed(7)
rand_tensor_2 = rand_tensor_2.normal(shape=(5, 5))

rand_tensor_3 = tf.random.Generator.from_seed(15)
rand_tensor_3 = rand_tensor_3.normal(shape=(5, 5))

rand_tensor_4 = tf.random.Generator.from_seed(23)
rand_tensor_4 = rand_tensor_4.normal(shape=(5, 5))

rand_tensor_5 = tf.random.Generator.from_seed(77)
rand_tensor_5 = rand_tensor_5.normal(shape=(5, 5))


rand_tensor_1, rand_tensor_2, rand_tensor_3, rand_tensor_4, rand_tensor_5

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
        [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 , -0.48293006]],
       dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018,  0.69211644],
        [ 0.84215707, -0.06378496,  0.92800784, -0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967, -0.29604465, -0.21134205,  0.01063002],
        [ 1.5165398 ,  0.27305737, -0.29925638, -0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714,  1.2132233 ,  0.46988967,  0.37944323]],
       dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ,  1.5222508 ,  0.59

In [23]:
# shuffle without seeds

tf.random.set_seed(42)
rand_tensor_1_sh = tf.random.shuffle(rand_tensor_1, seed=42)
rand_tensor_2_sh = tf.random.shuffle(rand_tensor_2, seed=2)
rand_tensor_3_sh = tf.random.shuffle(rand_tensor_3, seed=5)
rand_tensor_4_sh = tf.random.shuffle(rand_tensor_4, seed=6)
rand_tensor_5_sh = tf.random.shuffle(rand_tensor_5, seed=8)

rand_tensor_1_sh, rand_tensor_2_sh, rand_tensor_3_sh, rand_tensor_4_sh, rand_tensor_5_sh

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[ 1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
        [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 , -0.48293006]],
       dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[ 1.5165398 ,  0.27305737, -0.29925638, -0.3652325 ,  0.61883307],
        [-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018,  0.69211644],
        [ 0.04221033,  0.29037967, -0.29604465, -0.21134205,  0.01063002],
        [-1.0130816 ,  0.28291714,  1.2132233 ,  0.46988967,  0.37944323],
        [ 0.84215707, -0.06378496,  0.92800784, -0.6039789 , -0.1766927 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[-0.4390865 , -0.4129243 ,  0.35877243, -1.90

si no usamos ni seed de operacion ni global, vamos a obtener diferentes resultados en cada ejecucion de la operacion en cada ejecucion del programa entero.
si solo usamos seed global, vamos a obtener diferentes resultados en cada ejecucion de la operacion, pero si reiniciamos el programa vamos a obtener la misma secuencia de resultados

al usar seed de operacion, hay un contador que da un resultado para cada iteracion de la operacion, es decir, devolvera un resultado diferente por cada incrementeo del contador, cada ejecucion de la operacion, para resetear el contador hay que setear una seed global

ejemplo: si mezclamos poniendo un seed=42, cada vez que ejecutemos se va mezclar de forma diferente

In [24]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

pero si agragamos la seed global antes, entonces en cada re-run obtendriamos el mismo resultado

In [25]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

it looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed

> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

### Other ways to make tensors

In [26]:
# create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [27]:
# create a tensor of all zeros
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpyu arrays into tensors

the main difference between numpy arrays and tensorflow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [28]:
# you can also turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [29]:
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### getting information from tensors

when dealing with tensors you probably want to be aware of the following atributes:
* shape
* rank
* axis or dimension
* size



In [30]:
# create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [32]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
# get various attriubutes of our tensor

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimension (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the las axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))

Datatype of every element: <dtype: 'float32'>
Number of dimension (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the las axis: 5
Total number of elements in our tensor: 120
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


### Indexing tensors

Tensors can be indexed just like Python lists

In [34]:
some_list = [1, 2, 3, 4]
some_list

[1, 2, 3, 4]

In [35]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
some_list[:1]

[1]

In [37]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [38]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [39]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [40]:
# create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [41]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [42]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [43]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [44]:
# add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # los 3 puntos es como poner [:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [45]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand hte final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [46]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [47]:
tf.expand_dims(rank_2_tensor, axis=1) # insert new dimension in the middle

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [48]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Manipulating tensor (tensor operations)

**Basic operations**

+, -, *, /

In [49]:
# you can add values to a tensor using the addition operator

tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [50]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [51]:
# multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [52]:
# subtraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [53]:
# we can use the tensorflow built-in function too
tf.multiply(tensor, 10)
# using the tf function is faster than regular operations

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [54]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix multiplications**

In machine learning, matrix multiplication is one of the most common tensor operations

there are two rules our tensor (or matrices) need to fulfill if we're going to matrix multiply them:

1. the inner dimensions must match
2. the resulting matrix has the shape of the outer dimensions

In [55]:
# matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [56]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [57]:
tensor1 = tf.constant([[1, 2, 5],
                      [7, 2, 1],
                      [3, 3, 3]])
tensor2 = tf.constant([[3, 5],
                       [6, 7],
                       [1, 8]])
tensor1, tensor2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [58]:
tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [59]:
# matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [60]:
tensor.shape

TensorShape([2, 2])

In [61]:
# create a tensor (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [62]:
# try to matrix multiply tensors of same shape
tf.matmul(X, Y)

InvalidArgumentError: ignored

**resource:** Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [63]:
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [64]:
tf.matmul(tf.reshape(X, (2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [65]:
tf.reshape(X, (2, 3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [66]:
# can do the same with transpose

X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [67]:
# try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**the dot product**

matrix multiplication is also referred to as the dot product.

you can perfomr matrix multiplication using:
* tf.matmul()
* tf.tensordot()

In [68]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [69]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [70]:
# perform the dot product on X and Y (requires X or Y to be tansposed)

tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [71]:
# perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [72]:
# perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [73]:
# check the values of Y, reshape Y and transposed Y
print("normal y: ")
print(Y, "\n")

print("Y reshaped to (2, 3) ")
print(tf.reshape(Y, (2, 3), "\n"))

print("Y transposed: ")
print(tf.transpose(Y))

normal y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3) 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [74]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multi;lication rules

### Changing the datatype of a tensor

In [75]:
tf.__version__

'2.12.0'

In [76]:
# create a new tensor with default datatype (float32)

B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [77]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [78]:
# change from float32 to float16 (reduce precision)

D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [79]:
# change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [80]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### aggregating tensors

aggregating tensors = condensing them from multiple values to a smaller amount of values

In [81]:
# get the absolute values

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [82]:
# get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregations:
* get the mininum
* get the maximum
* get the mean of a tensor
* get the sum of a tensor

In [83]:
random_tensor = tf.random.Generator.from_seed(7)
random_tensor = random_tensor.normal(shape=(4, 5))
random_tensor

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018,  0.69211644],
       [ 0.84215707, -0.06378496,  0.92800784, -0.6039789 , -0.1766927 ],
       [ 0.04221033,  0.29037967, -0.29604465, -0.21134205,  0.01063002],
       [ 1.5165398 ,  0.27305737, -0.29925638, -0.3652325 ,  0.61883307]],
      dtype=float32)>

In [84]:
tf.size(random_tensor), random_tensor.shape, random_tensor.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=20>, TensorShape([4, 5]), 2)

In [85]:
print(f"the min is: {tf.reduce_min(random_tensor)}")
print(f"the max is: {tf.reduce_max(random_tensor)}")
print(f"the mean is: {tf.reduce_mean(random_tensor)}")
print(f"the sum is: {tf.reduce_sum(random_tensor)}")

the min is: -1.3240395784378052
the max is: 1.5165398120880127
the mean is: 0.05985281616449356
the sum is: 1.1970562934875488


**Exercise** with whatt we've learned, find tyhe variance and standard deviation of our tensor using tensorflow method

varianza = Varianza = media((valor - media)²)

desviacion estandar =  √(Varianza)

In [86]:
variance = tf.math.reduce_variance(random_tensor)
print(f"the variance is: {variance}")
print(f"the standard deviation is: {np.sqrt(variance)}")
print(f"the standard deviation is: {tf.math.reduce_std(random_tensor)}")

the variance is: 0.40937796235084534
the standard deviation is: 0.6398265361785889
the standard deviation is: 0.6398265361785889


### Find the positional maximum and minimum



In [87]:
# create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [88]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [89]:
# index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [90]:
# find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [91]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [92]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [93]:
# find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### squeezing a tensor (removing all single dimensions)

In [94]:
# create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [95]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [96]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One hot encoding

In [97]:
# create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# one hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [98]:
# specify custom values for one hot enoding
tf.one_hot(some_list, depth=4, on_value="hola", off_value="chau")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hola', b'chau', b'chau', b'chau'],
       [b'chau', b'hola', b'chau', b'chau'],
       [b'chau', b'chau', b'hola', b'chau'],
       [b'chau', b'chau', b'chau', b'hola']], dtype=object)>

### squering, log, square root

In [99]:
# create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [100]:
# square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [103]:
# square root (requires non-int type)
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [105]:
# find the log 
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [107]:
tf.math.sin(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([ 0.84147096,  0.9092974 ,  0.14112   , -0.7568025 , -0.9589243 ,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.4121185 ], dtype=float32)>

### tensors and numpy

tensorflow interacts beautifully with numpy arrays

In [108]:
# create a tensor directly from a numpy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [109]:
# convert our tensor back to a numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [110]:
# convert tensor J to a numpy array
J.numpy(), type(J.numpy)

(array([ 3.,  7., 10.]), method)

In [112]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [113]:
# the default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

**Note:** One of the main differences between a tensorflow tensor and a numpy array is that a tensorflow tensor can be run on a gpu or a tpu

### Finding access to GPUs

In [2]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Tue May 23 15:20:26 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it wheneve possible.